### ISSUE TITLE
Properly license the code

### ISSUE THREAD

**Issue by nox** [cavi-au/Consent-O-Matic#1]
There is no mention of any license anywhere in this project, be it MIT, GPL, proprietary or any other license. Could you clarify under which license you intend this to be released, @dkgof?

**Comment by dkgof** [comment]
We are unfortunately waiting on someone to decide on which open source licence, but i can say it will be some opensource licence, probably MIT or Apache.

**Comment by dkgof** [comment]
License has now been choosen as MIT.
