### ISSUE TITLE
Choice settings cannot be changed back and are not deleted when deleting extension

### ISSUE THREAD

**Issue by ibnn0** [cavi-au/Consent-O-Matic#107]
When changing choice of browser extension „consent-o-matic“ to „on all websites“ there is no Option of changing that setting back.
Please make these consent options available not only one time one direction. 
Now I can read in header my choice, but cannot change it back. 

In that context you explain:
„The Consent-O-Matic extension does not process any personal data. The only data that Consent-O-Matic stores (on your computer) are:

Your settings
A count of pop-ups interacted with
A count of clicks saved
To delete all this data, simply uninstall the browser extension.“

My finding in Safari on iPadOS is that settings persist deletion of app.
When you reinstall from App Store, settings like „act on all websites“ are still active and remembered. 
thisnis not as expected. 

This is not good for and not expected from a GDPR and consent handling app
Please make that available.

**Comment by dkgof** [comment]
When you chose to delete the addon from your browser, we as an extension, do not get to run any code, so if the browser does not delete the settings for the extension, that is unfortunately not anything we can fix, at least not to my knowledge.

If i delete the extension on chrome or firefox, it is "reset" on next installation, so it might be a problem with safari.

**Comment by dkgof** [comment]
The setting to "act on all websites" is not a setting of Consent-O-Matic, but a generic extension setting from the browser, so im affraid that is also not something we can change.

**Comment by ibnn0** [comment]
With your response I did some deeper discovery and found that setting and that it is deeply buried in iOS Safari settings.

In iPadOS-Settings -> Safari -> Extensions -> Consent-O-Matic -> Other Websites you find Options "ask"|"grant"|"do not grant".
This is what controls that behavior.

Consent-O-Matic is not involved in it and behaves fair.
In so far indeed that the settings survive the app deletion act is not controlled by Consent-O-Matic extension app and its deletion and clean-up behavior. 

Thank you for your comment.

**Comment by svnhub** [comment]
Thanks for diving into it! I'll close the issue
