### ISSUE TITLE
Setting for people who don't care but just want the annoying shit to go away

### ISSUE THREAD

**Issue by michaelmadsen72** [cavi-au/Consent-O-Matic#108]

**Comment by michaelmadsen72** [comment]
This retarded politician solution which should have been implemented in the browsers themselves rather than in every single homepage on the planet, is for many people an annoyance. But Consent-O-Matic in many cases also take several seconds or even minutes to do it's thing, which is also annoying.
I miss a setting called: "just close the fucking dialog regardless of my privacy"

**Comment by svnhub** [comment]
You're lucky! There's a hidden get-rid-of-annoying-shit-feature. You just need to find it in the secret settings, like a ninja.
![image](https://user-images.githubusercontent.com/13135124/192542453-c2574ca1-b244-4764-9c4d-32b60a22dfbf.png)

If you like it let us know! We may even make it less ninja in a future version of the extension. Oh and it still fills out the popups as best as it knows according to your settings - it just hides annoying shit while doing so.

**Comment by dkgof** [comment]
The next version, when released, has a choice of mode between picture in picture, and hiding completely like before.

Not entirely sure when this release is due, but it is in the making.

**Comment by luetage** [comment]
For anyone wondering how to get to the debug button… I can’t tell you how. Instead open devtools and set `#debugTab` to display block.

**Comment by j4k0xb** [comment]
> For anyone wondering how to get to the debug button… I can’t tell you how. Instead open devtools and set `#debugTab` to display block.

just move your mouse to this location and click (its invisible)

![image](https://user-images.githubusercontent.com/55899582/193070807-377802d0-ef1f-464c-8bfa-6ee03130410e.png)

**Comment by dkgof** [comment]
The debug button is just hidden, you can still click it.

**Comment by svnhub** [comment]
I'll just close this issue as the extension mostly focuses on working within the current (retarded) political framework by attempting to fill out the popups according to user preferences.
An even more aggressive approach to getting rid of tracking and cookie popups as well as other nuisances could in theory be possible if someone hosted that kind of rules in a separate repository. Such rules could be added under rule lists in the extension.
