### ISSUE TITLE
Firefox seems to implement their own version

### ISSUE THREAD

**Issue by yoshimo** [cavi-au/Consent-O-Matic#109]
https://bugzilla.mozilla.org/show_bug.cgi?id=1783015 
with general rules, exceptions and site specific rules.

**Comment by yoshimo** [comment]
It is not as detailed as COM though and i wonder if we should port the detailed approach to firefox?

**Comment by svnhub** [comment]
We don't really track this as an issue any differently from any of the other extensions in this same space of controlling consent (even though this is/was/may be a built-in feature). Mozilla actually reached out before implementing the solution to share ideas and concerns. We encourage all solutions that can empower people to more easily communicate their data-sharing preferences to websites they visit.
