### ISSUE TITLE
Support for Android. Screen overlay.

### ISSUE THREAD

**Issue by DipperDK** [cavi-au/Consent-O-Matic#112]
Hi

I'm not a programmer my self, but could it be possible to get the Consent-O-Matic to Android, to work with browsers like Chrome, Firefox, Opera, Samsung internet etc.? Maybe like a screen overlay like on a password manager?
That would be so cool, and so great.
Hope you can develop something like that. The sooner the better.
In advance, thanks.

Best Regards
DipperDK

**Comment by dkgof** [comment]
Unfortunately that is not something that can be used to make Consent-O-Matic work on Android.

At the moment, only firefox has support for extensions, and they have locked it to a select few, until this changes we have no way to support android browsers :(
