### ISSUE TITLE
www.numerama.com - cookie banner still showing

### ISSUE THREAD

**Issue by casualkitten1** [cavi-au/Consent-O-Matic#114]
Hello, the banner can still be seen on this website.

Example : https://www.numerama.com/tech/688711-voici-a-quoi-ressemblera-vlc-4-0-et-son-look-plus-moderne.html

Thanks in advance!

**Comment by dkgof** [comment]
SirData CMP has made changes to how their popup looks, and this has triggered, that CoM runs through tons of elements to try and find the checkboxes. It needs a rule rewrite.

**Comment by dkgof** [comment]
I updated the CMP. To force the update to get used faster. You can click "Update Rules Now" under "Rule List" tab in settings.

**Comment by casualkitten1** [comment]
Yup, it's fixed. 

Thanks @dkgof !
