### ISSUE TITLE
[Feature request] Consider allowing users to disable or tone down the phone-home feature

### ISSUE THREAD

**Issue by SonephetR2** [cavi-au/Consent-O-Matic#117]
In the plugin's settings, I was surprised to see that "All the rule lists are updated automatically every 15 minutes". This seems like overkill and could be construed as a phone-home feature to some extent. Could you perhaps offer users the option to update automatically every week rather than every 15 minutes and also to disable that option and only keep manual on-click updates? Thanks!

**Comment by jdreesen** [comment]
Hasn't this already been changed in https://github.com/cavi-au/Consent-O-Matic/issues/89#issuecomment-1245029535?

**Comment by SonephetR2** [comment]
Sorry, I didn't catch that. I'm using V.1.0.10 from the Firefox extensions directory and this change was supposed to have been implemented in V.1.0.9, however. It's probably just a case of non-updated text then.

**Comment by dkgof** [comment]
I can confirm that this is only a matter of the rendered string, it has actually been changed to a random interval between 22-48 hours.

The description will be fixed with the next release.
