### ISSUE TITLE
EZ cookie manager not handled?

### ISSUE THREAD

**Issue by MarkieMark** [cavi-au/Consent-O-Matic#119]
(Feature request I think)
(Chrome 106.0.5249.119 (Official Build) (64-bit))

These kinds of dialogues are quite frequent on various websites (here for instance https://www.c-programming-simple-steps.com/); personally I'd rather object to the "legitimate" interest obnoxiousness, though consent-o-matic seems not to handle the dialogue for me?
![image](https://user-images.githubusercontent.com/234057/196132028-1a9a8821-1fbd-4018-a6c6-fe2e6c2a12ef.png)

**Comment by dkgof** [comment]
I have updated the rule for the ez-cookie cmp, it seems they changed it since the rule was first created.

It now tries handles legitimate interest aswell.

**Comment by M1Aston** [comment]
It doesn't work. Cookie handling never stops:
https://autorai.nl/
