### ISSUE TITLE
provide instructions on how to build from source

### ISSUE THREAD

**Issue by arielelkin** [cavi-au/Consent-O-Matic#120]
I'm trying to build this extension for Chrome, but I get build errors when I try to build the xcode project in xcode/Consent-O-Matic.xcodeproj

Seems like the files in the Extension/ directory haven't been added to the xcode project. If I add them the project builds, but I can't figure out how to produce a crx file for Chrome?

**Comment by dkgof** [comment]
XCode is for building the safari ios/macos variant of the extension.

For chrome you can just check out git, and load it as an unpacked extension:

https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#load-unpacked

**Comment by arielelkin** [comment]
thanks, i made a PR to clarify the documentation accordingly: https://github.com/cavi-au/Consent-O-Matic/pull/121
