### ISSUE TITLE
dialog-polyfill.css issue

### ISSUE THREAD

**Issue by prismsoundzero** [cavi-au/Consent-O-Matic#16]
Hi there,

I discovered an issue with your extension. On a website I am using, dialogs were not shown properly. When I looked at the developer panel, I discovered that your extension was injecting a css file `dialog-polyfill.css` that was causing the `<dialog>` element of the page to have the display property set to none:

`dialog:not([open]) {
   display: none;
}
`

**The real issue is that even if I uncheck "Keep running on this site?" the css is still injected and is causing the issue.** I am forced to disabled completely the extension to make the website work.

**Comment by dkgof** [comment]
It is the Dialog polyfill:

[https://github.com/GoogleChrome/dialog-polyfill](https://github.com/GoogleChrome/dialog-polyfill)

that is setting up these CSS rules. Im a little confused to what your problem is, since that css rule states that dialogs that are not open, should be hidden, which to me seems perfectly sensible.

Are you using dialogs and calling show / showModel on the dialog element?

This should work perfectly with the polyfill enabled.

**Comment by prismsoundzero** [comment]
That's not a website I own so I don't really know how they are using the dialog element but I assume they are not using it as a standard dialog element. It appears that they have a css rule that makes all dialog elements displayed as a block regardless of the presence of the open attribute and that the polyfill is overriding this rule setting the display property to none. But anyway that's not really the point.

What I don't understand is why this polyfill is injected even if the extension is disabled for this particular website. I would assume that unchecking the "Keep running on this site?" checkbox would disable the extension for the site and thus would not inject anything on the page. That would prevent the extension to break a website.

**Comment by dkgof** [comment]
Right, i think i misread it thinking you were doing something with dialog yourself, sorry about that.

Currently the dialogpolyfill is injected by the extension manifest directly, so it gets injected even if a website is disabled for processing, ill look into changing this to only inject it when needed.

**Comment by prismsoundzero** [comment]
No problem ;)

I have just checked the `<dialog>` element as I never used it before and I can see that only Chrome (and the derived browsers) has an implementation of the dialog element spec. It does not seem really a standard.

So maybe you should also add `.ConsentOMatic-Progress-Dialog` class selector on all the rules in the `dialog-polyfill.css`, that would prevent your extension to change the look and feel of other dialog elements contained in the visited websites.

**Comment by LucileDT** [comment]
I agree with @prismsoundzero, and this is related to #28

**Comment by dkgof** [comment]
The latest version no longer uses dialogPolyFill. (0.9.3)
