### ISSUE TITLE
Possible performance issue?

### ISSUE THREAD

**Issue by gwarser** [cavi-au/Consent-O-Matic#17]
I was writing new message here: https://github.com/uBlockOrigin/uBlock-issues/issues/1027

and my browser slowed down to a crawl. It was not possible to type, because characters appeared on screen in second long intervals. Recorded profile shown 
Consent-O-Matic on top. I disabled it in about:addons and issue stopped immediately.

I have many extensions and it seems GitHub was inserting new messages into the thread at this time, so it does not seem to be easily reproducible.

Hmmmm, looking at the profile, Refined GitHub is responsible for nearly half of the slowdown. Maybe some weird racing issue?

https://profiler.firefox.com/public/f14bf159d0597d898c0a44c7534d883e85ec2fe3/calltree/?globalTrackOrder=0-1&localTrackOrderByPid=1249-1-2-0~3798-0-1~&thread=2&v=4

***

It's all in `querySelectorAll`.

**Comment by dkgof** [comment]
I cannot seem to replicate this behavior, maybe a conflict with one of your other extensions.

**Comment by gwarser** [comment]
Yes, this is possible. Also this: https://bugzilla.mozilla.org/show_bug.cgi?id=1633409

I will reopen if ever happens again.
