### ISSUE TITLE
Doesn't work on https://www.mgmresorts.com/en.html

### ISSUE THREAD

**Issue by Endle** [cavi-au/Consent-O-Matic#178]
Windows 10 Firefox 109.0.1 (64-bit)

With this plugin on, the whole webpage is grey. I'm disallowed to click anything on this page.

When turned Consent-O-Mac, a consent info appears at the bottom of the webpage

![image](https://user-images.githubusercontent.com/3221521/216845444-05df29e8-f95c-4dce-867c-b025b928b6f7.png)

**Comment by svnhub** [comment]
Does this still happen? It doesn't seem to be popping up anything for me

**Comment by Endle** [comment]
I can't reproduce this issue now. I guess that MGM had some front-end issue when they were promoting F1, and such code had been removed from their site then.

Maybe I should close this issue?
