### ISSUE TITLE
good idea, but

### ISSUE THREAD

**Issue by M1Aston** [cavi-au/Consent-O-Matic#18]
This add-on is a great idea. Just a shame it fails on many sites. Generating my own rules... well, that won't work.

Is it actively being developed\improved?

**Comment by dkgof** [comment]
Unfortunately atm we dont have much time to actively work on this project, as it was for a research paper that has since been completed.

If we get more time that allows us to work on it, we will try and improve it.

**Comment by LucileDT** [comment]
@dkgof do you welcome pull requests on this project?

**Comment by jaluth** [comment]
@LucileDT I submitted #29 about a month ago, but haven't heard back yet. Here's hoping @dkgof has notifications enabled.

**Comment by dkgof** [comment]
Pull requests are very welcome.

**Comment by svnhub** [comment]
Version 1.0.0 is releasing and should hopefully work on many more sites - pull requests with new rules are still very welcome
