### ISSUE TITLE
Slow operation making unusable - Firefox add-in

### ISSUE THREAD

**Issue by Eggthang** [cavi-au/Consent-O-Matic#180]
have used for some time but in last 72 hours has run extremely slowly on Firefox (possibly since Firefox update?) effectively blocking access to some websites. E.g. went to URL https://www.cyclingweekly.com/ about 4 hours ago. As of now add-in is still processing sourcepoint-frame-2022... on the website home page and while running (visible in pop-up) the webpage is not navigable

**Comment by ak1dd** [comment]
I'm having the same thing on more and more websites..  The automated window pops up and either stops processing or appears to loop over and over and over.  I submit them as I see them but today I had yet another so thought I'd see if someone else has reported.   When it does this, the target site is inaccessible until I completely disable consent-o-matic or disable on the site.

https://www.pcgamer.com/20-years-on-this-mod-adds-new-lightsabers-character-models-and-quality-of-life-fixes-to-one-of-the-best-star-wars-games/

**Comment by zjeffer** [comment]
Same thing here on techradar. Did they add protections against this addon or something?

**Comment by Kylotan** [comment]
I'm seeing this too - it seems to be specific to the Sourcepoint consent-management platform.
(Funnily enough, the consent pop-up on https://sourcepoint.com/  is handled very quickly by the plugin. It's on 3rd party sites where it often struggles.)

**Comment by gburning** [comment]
Same on Techradar. Is there a way of disabling the plugin for certain types of consent walls until there is a fix?

**Comment by dkgof** [comment]
I have identified the problem, and a fix is in the pipeline. Unfortunately it was not enough with a rule change, so a new version of COM is inbound aswell. (Hopefully tomorrow when i get it ready)

**Comment by dkgof** [comment]
This should now be fixed, as soon as 1.0.12 is reviewed and allowd on the extension stores. (iOS will take a little while longer).

**Comment by zjeffer** [comment]
Can confirm it is fixed on Techradar. Thanks!
