### ISSUE TITLE
google-cwiz doesn't work on mobile

### ISSUE THREAD

**Issue by jonathanjameswatson** [cavi-au/Consent-O-Matic#196]
When the browser's user agent string indicates that the device is a mobile, the Google consent page has different text. In particular, the section about the Google Analytics opt-out browser extension is missing. This breaks the google-cwiz rule, as it has the following present matcher:

```
{
    "type": "css",
    "target": {
        "childFilter": {
            "target": {
                "selector": "a[href^=\"https://policies.google.com/privacy\"]"
            }
        },
        "selector": "body[jscontroller] c-wiz",
        "textFilter": "Google Analytics"
    }
}
```

Here is an image with the desktop version on the left and the mobile version on the right:

![image](https://user-images.githubusercontent.com/23344719/219093448-5a3f5a73-3bbe-48ec-9adb-a0e1a1930db9.png)

**Comment by bbsixzz** [comment]
Is this being worked on?

**Comment by bbsixzz** [comment]
This seems to have regressed in 1.1.0 iOS 17.5.1
