### ISSUE TITLE
Provide guidelines for website developers so Consent-O-Matic can handle their website

### ISSUE THREAD

**Issue by Colossus** [cavi-au/Consent-O-Matic#207]
I'm going to take a website online soon that optionally uses cookies/localStorage and I want it to play nice with Consent-O-Matic. Are there any guidelines on how to achieve this? Like certain HTML attributes or button/checkbox labels or aria labels to tell Consent-O-Matic what the "accept necessary cookies"/"accept third party cookies"/"reject all cookies" buttons are?

In case you think this is a malicious request to confuse Consent-O-Matic into accepting all cookies by setting wrong attributes, requiring certain visible button texts or aria labels for the "accept necessary"/"accept all"/"reject all" buttons or checkboxes would ensure that this is not the case.

**Comment by dkgof** [comment]
The most common problem, is obfuscation in the code, that hides the intent of the consent form.

So if you want to be very easy to write a rule for, then use describing classes on the buttons. "acceptAll", "rejectAll", "openSettings" etc. And use classes for the consent category buttons aswell, so it is easy to see what consent the button will grant. Something like class="consentMarketing" or class="consentAnalytics". This way we can have an easy to write rule, that does not change, even if the site is translated, as we dont have to resort to parsing the text to find out what type of consent it is.

So, clearly marking what stuff is, from the code side, not just with text, makes it very easy to write a nice consent rule.

**Comment by Colossus** [comment]
ok that sounds great. As a small request, I'm wondering if you could add this info to your website at https://consentomatic.au.dk/ so it's easier to find

**Comment by dkgof** [comment]
Maybee, its not really the sort of information that the vast majority of ConsentOMatic users would need :D
