### ISSUE TITLE
race condition?

### ISSUE THREAD

**Issue by RiedleroD** [cavi-au/Consent-O-Matic#241]
https://downdetector.com has a cookie banner that isn't being reliably blocked. After reloading the site with cache on, it worked, but I suspect there's some issue with the C-O-M being faster than the site can load.

I'll maybe have a look tomorrow. maybe. Probably not. I hate debugging race conditions.

**Comment by svnhub** [comment]
Does it popup slower than 5s for you?

**Comment by RiedleroD** [comment]
can't reproduce anymore, closing.
