### ISSUE TITLE
Endless consent loop: Gfycat

### ISSUE THREAD

**Issue by Nezteb** [cavi-au/Consent-O-Matic#259]
Disclaimer: I am on the Arc browser: https://arc.net/ (based on Chromium)

1. Have `Consent-O-Matic` installed
2. Open https://gfycat.com/
3. The consent popup will be handled and redirect to the consent customization form
4. The consent popup shows up again on the customization form page
5. GOTO 3

I don't know if this is related to: https://github.com/cavi-au/Consent-O-Matic/pull/228

**Comment by svnhub** [comment]
Site has shut down in the meantime, please re-open issue if it happens somewhere else where it can be debugged
