### ISSUE TITLE
block connection to caisse-epargne.fr

### ISSUE THREAD

**Issue by Saimyx** [cavi-au/Consent-O-Matic#26]
This extension blocks the connection to the site https://caisse-epargne.fr/particuliers : you cannot enter the code received by SMS.
I post this issue not to complain (I think this extension is great), but to inform users. I spent a lot of time looking for what was blocking my access…

**Comment by LucileDT** [comment]
@Saimyx do you think this is related to #28 and #16?

**Comment by dkgof** [comment]
I can not open the page in question at all.
