### ISSUE TITLE
TypeError: MutationObserver.observe: Argument 1 is not an object.

### ISSUE THREAD

**Issue by imagoiq** [cavi-au/Consent-O-Matic#266]
Error visible for example on this website: https://cloud.pix4d.com/demo
when opening the devtools:

![firefox_CRiP3Kb7Ju](https://user-images.githubusercontent.com/12294151/231396119-f1dce399-0262-4e22-95e0-8305c52584a1.png)

Firefox: 112.0b9 (64-bit) Windows 10

**Comment by togamid** [comment]
The problem seems to be that document.querySelector("html") seems to return null while the extension is loaded

**Comment by svnhub** [comment]
This is related to #343

**Comment by svnhub** [comment]
Fixed in the next release, Consent-O-Matic no longer tries to run on content that isn't text/html
