### ISSUE TITLE
Firefox Mobile Support (Android)

### ISSUE THREAD

**Issue by ryanwalder** [cavi-au/Consent-O-Matic#267]
Support for Firefox Mobile would be excellent if at all possible.

I'm not sure of the process of getting an extension/addon approved by Mozilla but Firefox Nightly can load non-approved extensions.

https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/

**Comment by MidasN** [comment]
We've been in communication with the Mozilla add-on team but they're currently not admitting any new add-ons to their recommended programme unfortunately. It sounds like they are doing a bit of spring cleaning of what they have and want to finalise that before opening it up again.

**Comment by templesnr** [comment]
It looks like the same thing for Chrome - is that right?
I love this extension, thank you for all your hard work.

**Comment by FantaMagier** [comment]
You can use the Kiwi browser and install the add-on there. It's not perfect, but it works.

**Comment by DickinsonSa** [comment]
> .

Can you explain what you mean by 'it's not perfect'. Looking for a good solution myself.

**Comment by FantaMagier** [comment]
It works completely, but is not native like a Firefox extension.

**Comment by DickinsonSa** [comment]
> It works completely, but is not native like a Firefox extension. 

Thank you clarifying that.

**Comment by yoshimo** [comment]
Firefox Nightly has the option to automatically handle consent windows and if you encounter a site that isn't handled yet by mozilla rules, you can report it.

**Comment by svnhub** [comment]
Also Firefox Nightly now allows you to link to addon collections. Feel free to put Consent-O-Matic in one and try it out and report back how well it works (wanted to try it myself but havent had the time yet):
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by ryanwalder** [comment]
Looks like Firefox are rolling out the ability to install any extension on Android. 

https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/

Kinda makes this redundant so will close.

**Comment by JohnVeness** [comment]
> Firefox Nightly has the option to automatically handle consent windows and if you encounter a site that isn't handled yet by mozilla rules, you can report it.

Hi, can you link to more information about this? I've tried searching with no luck yet!

**Comment by yoshimo** [comment]
https://github.com/mozilla/cookie-banner-rules-list
