### ISSUE TITLE
A big thanks

### ISSUE THREAD

**Issue by m4l3z** [cavi-au/Consent-O-Matic#27]
This app is saving me a lot of time and making browsing on the internet way more pleasant.
Thanks for all the hard work you put it and know that it is useful to many.

<3

**Comment by blackthornedk** [comment]
I just want to chip in!
I really like the idea of this add-on.

I've seen other approaches, that just block the cookies and popups, but this actually show the site owners, how my preferences are chosen. Perhaps I can help persuade them to limit tracking that way. :)

**Comment by jaluth** [comment]
What @m4l3z and @blackthornedk said. The documentation is a bit unclear to a non-frontend'er like me. That said, I'd love to figure out how to make some meaningful contributions to rules.json. For now, I have submitted a PR for an updated README.md. 😃

**Comment by VictorieeMan** [comment]
Let me join in the thank-you choir 👍 

Consider setting up some donations systems!
Suggestions:
*Brave Rewards with GitHub integration
*A support/donation link in the repository
*GitHub's own sponsorship program
