### ISSUE TITLE
How do DOM selectors work in the rules editor?

### ISSUE THREAD

**Issue by jalemann** [cavi-au/Consent-O-Matic#276]
Background: I was trying to add some rules, e.g. for https://www.call-a-pizza.de and I'm using the Rules Editor as somehow pulling a json from a repo didn't seem to work even when hitting the Update Rules Now button a few times.

I was trying to use the CheckboxMatcher as the cookie box contains e.g. `<input type="checkbox" id="functional_cookies" name="functional_cookies" value="1">` which contains type checkbox. I looked up how DOM selection works and set the target DOM node selector to `#functional_cookies` which leads to `Error toggling: Error: No checkbox found, cannot check state` because `findElement: #functional_cookies` yields `Returned result: undefined`.

I don't quite understand why though. If I use the dev tools console and run `console.log(document.querySelector("#functional_cookies"));` it returns `<input id="functional_cookies" type="checkbox" name="functional_cookies" value="1">` as expected and mentioned above.

**Comment by dkgof** [comment]
If you could export your current rule from the editor, and paste it somewhere.

It should work as you describe it, but some actions "anchor" the root that the querySelector is called from, so it is not always from document.

Therefor without seeing the rest of the code, it is hard to tell what the problem is.

**Comment by jalemann** [comment]
This is the json code as exported by the rules editor:

```
{
    "$schema": "https://raw.githubusercontent.com/cavi-au/Consent-O-Matic/master/rules.schema.json",
    "call-a-pizza.de": {
        "detectors": [
            {
                "presentMatcher": [
                    {
                        "type": "css",
                        "target": {
                            "selector": ".cookies_modalbox"
                        }
                    }
                ],
                "showingMatcher": [
                    {
                        "type": "css",
                        "target": {
                            "selector": ".cookies_modalbox"
                        }
                    }
                ]
            }
        ],
        "methods": [
            {
                "name": "HIDE_CMP"
            },
            {
                "action": {
                    "type": "click",
                    "target": {
                        "selector": ".cookie_link"
                    }
                },
                "name": "OPEN_OPTIONS"
            },
            {
                "action": {
                    "type": "list",
                    "actions": [
                        {
                            "type": "consent",
                            "consents": [
                                {
                                    "matcher": {
                                        "type": "checkbox",
                                        "target": {
                                            "selector": "#functional_cookies"
                                        }
                                    },
                                    "toggleAction": {
                                        "type": "click",
                                        "target": {
                                            "selector": "#functional_cookies"
                                        }
                                    },
                                    "type": "A"
                                }
                            ]
                        },
                        {
                            "type": "consent",
                            "consents": [
                                {
                                    "matcher": {
                                        "type": "css",
                                        "target": {
                                            "selector": "#marketing_cookies"
                                        }
                                    },
                                    "toggleAction": {
                                        "type": "click",
                                        "target": {
                                            "selector": "#marketing_cookies"
                                        }
                                    },
                                    "type": "F"
                                }
                            ]
                        }
                    ]
                },
                "name": "DO_CONSENT"
            },
            {
                "action": {
                    "type": "click",
                    "target": {
                        "selector": ".cookies_save_settings"
                    }
                },
                "name": "SAVE_CONSENT"
            },
            {
                "name": "UTILITY"
            }
        ]
    }
}
```

**Comment by dkgof** [comment]
The site "call-a-pizza.de" is not working for me, i wonder if its because im not in germany?

At a quick glance, the rule looks ok. The other matcher should be a checkbox matcher aswell, or else the toggle action will not work as expected. Since a css matcher that "matches" means that that consent is "active". The checkbox matcher actually looks at the input and sees if its "active" or not.

**Comment by dkgof** [comment]
One thing it could be, is maybee your rule is run to soon, maybee the ".cookies_modalbox" is present on the page before the consentbox is ready? So the box is detected, but the input's are not in the dom yet.

You can try to enable "display" filter for the css selector of ".cookies_modalbox" or you can insert a waitcss in the top of you action list, and let it wait for some css selector that is present only when the popup box is completely ready.

**Comment by jalemann** [comment]
Oh yeah I also tried whether the CssMatcher would work where the CheckboxMatcher wouldn't and forgot to change it back.
The Waiting did the trick (however I used WaitCssAction to wait for the checkbox selectors to be found). Thank you for your help.
Another thing that didn't work as I expected was the toggleAction, somehow it enabled all cookies even those I set to false. Still the easy workaround is to just use trueAction and falseAction where the checkbox is only clicked if true and wait 0 is done if false.

If there is a better way for do nothing if false, please let me know.
