### ISSUE TITLE
flightradar24.com & onetrust sdk issue

### ISSUE THREAD

**Issue by Seldaek** [cavi-au/Consent-O-Matic#278]
https://www.flightradar24.com fails to load (I get a gray overlay over the whole page rendered by a div with id `onetrust-consent-sdk`) when Consent-O-Matic is enabled. When disabling it I see a cookie consent popup and then all works fine, so I'm guessing there is an issue here.

**Comment by jalemann** [comment]
Seems to work for me.
There is a transparent grey overlay which darkens the map which appears and stays even with all blockers and Consent-O-Matic disabled and filling out the cookie consent popup manually. To me it seems like that's intended.

**Comment by Seldaek** [comment]
I see this by default:

<img width="1177" alt="image" src="https://github.com/cavi-au/Consent-O-Matic/assets/183678/5839011a-b49f-4878-894c-a9c412aaf0ee">

Then this if I disable consent-o-matic

<img width="1188" alt="image" src="https://github.com/cavi-au/Consent-O-Matic/assets/183678/98e4ad2a-6c27-49f9-a5b6-d21847aa164e">

Then this after I click on the consent manually

<img width="1184" alt="image" src="https://github.com/cavi-au/Consent-O-Matic/assets/183678/2d60bd0e-6c5d-48f1-859c-57fd817b7e8a">

As you can see the overlay is gone. The map is still darkened slightly to highlight the planes, but in the first screenshot I cannot interact with the page at all.

**Comment by jalemann** [comment]
Thanks for the screenshots, I see.
The overlay I meant is the one in the last screenshot which as you said puts the focus on the planes.
However the darker overlay doesn't appear for me and the cookie consent popup looks quite different for me.
Maybe because I'm based in the EU?

**Comment by alcayaga** [comment]
Happens with me too (Outside the EU)

The cookie popup appears for one second and then I get the gray overlay.
