### ISSUE TITLE
Injected CSS hides the two-factor auth modal on Rocket Chat

### ISSUE THREAD

**Issue by Em-AK** [cavi-au/Consent-O-Matic#28]
I can not type in the Two-factor auth input form on Rocket-chat.
Wheter I try to login while two-factor auth is activated, or when I try to deactivate two-factor auth from `/account/security` route.

### Consent-O-Matic Extension enabled in brave://extensions/

Checking/unchecking the "Keep running on this site?" option for the extension has no effect.
![2021-01-12-155818_1533x716_scrot](https://user-images.githubusercontent.com/1518393/104331501-6d252580-54ef-11eb-84ce-8bd868a736ac.png)

### Consent-O-Matic Extension disabled in brave://extensions/
![2021-01-12-160318_1540x844_scrot](https://user-images.githubusercontent.com/1518393/104331765-ba08fc00-54ef-11eb-8c6e-ede86e7cbb6e.png)

**Comment by Em-AK** [comment]
It would be great to be able to exclude some trusted sites with a blocklist to desacivate the extension.

**Comment by LucileDT** [comment]
It happens on all the RocketChat modals, preventing users to do actions involving them (e.G. upload a picture, connect with two factors authentication...).

**Comment by dkgof** [comment]
The latest version 0.9.3 does no longer use dialogPolyFill, this should fix this issue.
