### ISSUE TITLE
Cookie popup comes back if I press space

### ISSUE THREAD

**Issue by lrasinen** [cavi-au/Consent-O-Matic#282]
Website: https://thenewstack.io (but happens elsewhere as well)

I use the space bar to scroll web sites, especially ones with lots of text. After installing Consent-O-Matic, it often happens so that when I hit space, the consent popup comes back on screen.

The simple workaround is to click on the page to make sure the input focus isn't on the popup (even if hidden), but it would be nice if the extension would clean up after itself, so to speak.

**Comment by svnhub** [comment]
This should be fixed in the next release
