### ISSUE TITLE
Breaks leagueofcomicgeeks.com

### ISSUE THREAD

**Issue by skymoo** [cavi-au/Consent-O-Matic#283]
With the extension enabled when I load any page at https://leagueofcomicgeeks.com I get redirected to:

https://leagueofcomicgeeks.com/search?keyword=

With an error stating:

```
An Error Was Encountered

Please enter a search term to continue.

Click Here to Go Back or Return to the Homepage
```

Seems to be similar to #281

**Comment by dkgof** [comment]
I believe this has now been fixed with PR #295.
