### ISSUE TITLE
Redirectio when navigating to learn.microsoft.com

### ISSUE THREAD

**Issue by paulomorgado** [cavi-au/Consent-O-Matic#284]
On some pages on learn.microsoft.com, Consent-O-Matic redirects to https://learn.microsoft.com/en-us/search/

For example, https://learn.microsoft.com/en-us/certifications/exams/ai-900/ redirects to https://learn.microsoft.com/en-us/search/?category=Certification

Only disabling the extension will stop this behavior.

Microsoft Edge Version 113.0.1774.57 (Official build) (64-bit)
Windows 11 22H2

**Comment by MarkusRodler** [comment]
I can confirm the issue

**Comment by gioxx** [comment]
Yes, I have the same problem.

**Comment by paulomorgado** [comment]
Just tried with https://learn.microsoft.com/en-us/dotnet/core/diagnostics/sos-debugging-extension and it still happens.
