### ISSUE TITLE
Microsoft Learn Redirects?

### ISSUE THREAD

**Issue by irrigate-hanks** [cavi-au/Consent-O-Matic#293]
While this add-on is enabled, any and all links to Microsoft Learn pages are redirected to a generic ML search page.

Clicking into the following link from a Google search:
https://learn.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpn-devices

Redirects to the following link a second or two after loading:
https://learn.microsoft.com/en-us/search/?scope=Azure&fromNavSearch=true

Unchecking 'keep running on this site?' or outright disabling the add-on resolves the issue. Nevertheless, thought this was an interesting side effect of the add-on.

**Comment by iw0nderhow** [comment]
This is already being discussed in #281

**Comment by paulomorgado** [comment]
Just tried with https://learn.microsoft.com/en-us/dotnet/core/diagnostics/sos-debugging-extension and it still happens.

**Comment by dkgof** [comment]
Are you sure that the rules was updated in your Consent-O-Matic?

It does not happen here anymore. Try going to the extension settings, "Rules", "Force update" and try again.

**Comment by paulomorgado** [comment]
> Are you sure that the rules was updated in your Consent-O-Matic?
> 
> It does not happen here anymore. Try going to the extension settings, "Rules", "Force update" and try again.

That's what's missing. Thanks.
