### ISSUE TITLE
Does not always handle "legitmate interest" objection opt-outs. 

### ISSUE THREAD

**Issue by thomashillman** [cavi-au/Consent-O-Matic#31]
Fantastic idea and brilliant implementation. Just needs to be able to handle the "more option" legitimate interest selections e.g. Object All.
![File](https://user-images.githubusercontent.com/1469810/123808334-904e6080-d8e8-11eb-8595-fb5506674c31.jpg)

**Comment by svnhub** [comment]
For huffpost.com the quantcast2b rule was updated to include legitimate interests. This will be included in the next release.
In general more focus has been put on the legitimate interest claims of the CMPs with the new rules soon to be released. Their claim may actually be illegal but that is another discussion entirely.

**Comment by svnhub** [comment]
Version 1.0.0 with the fix for this issue is being released very soon. Closing the issue.
