### ISSUE TITLE
Dead news link

### ISSUE THREAD

**Issue by ducalpha** [cavi-au/Consent-O-Matic#33]
The link `https://www.prosa.dk/artikel/virksomheder-narrer-brugerne-til-mere-dataovervaagning/` on `README.md` seems dead. It said:
```
The news record is not available anymore.
Kommentarer
Log på Mit PROSA for at se eller skrive en kommentar til artiklen

The news record is not available anymore.
```

**Comment by jaluth** [comment]
@ducalpha PROSAs CMS is odd. Luckily the Wayback Machine has a cached version. Fixed in https://github.com/cavi-au/Consent-O-Matic/pull/34
