### ISSUE TITLE
Downloaded on iPhone 

### ISSUE THREAD

**Issue by Texasaaa** [cavi-au/Consent-O-Matic#337]
when I downloaded your program on my iPhone, it wanted me to download github. It never did say anything about consent-o-Matic. And of course it didn’t block any cookies when I looked at the webpage.
Is there a simple note that shows how to set up an iPhone with consent-O-Matic and make it work?
This all looks like it’s made for very advanced computer users, when in fact, we need this for the general public who knows basically nothing 🤷🏻‍♂️. If you can help in anyway, I sure would appreciate it because I hate cookies! Thank you

**Comment by svnhub** [comment]
Have a look at the App Store from the iPhone and download the program from there. GitHub contains the source code for the program and is indeed not meant to be used directly by (most) users

https://apps.apple.com/xk/app/consent-o-matic/id1606897889?platform=iphone
