### ISSUE TITLE
`contentScript.js` runs on an SVG image, causing the mutationobserver to fail

### ISSUE THREAD

**Issue by slippycheeze** [cavi-au/Consent-O-Matic#343]
origin: https://cs.au.dk/news-events/consent-o-matic
SVG: https://cdn.au.dk/2016/assets/img/logos.svg#au-en

Your `contentScript.js` function `contentScriptRunner` is executed in the SVG document `logos.svg` when viewing the top level article page.  It fails, because there is no HTML element to watch.

It probably shouldn't be running at all; since that isn't practical, checking `document.contentType`, or perhaps just for `document.querySelector("html") === null`, would allow returning early.

https://github.com/cavi-au/Consent-O-Matic/blob/master/Extension/contentScript.js#L100
```js
async function contentScriptRunner() {
    // the failure is here, because `document.querySelector("html")` returns null:
    // there *is* no `html` element in this document, just SVG :)
    observer.observe(document.querySelector("html"), {
        childList: true
    });
    // ...
}
```

```js
JSON.stringify(document.location); // =>
{
  "ancestorOrigins": {"0": "https://cs.au.dk"},
  "href": "https://cdn.au.dk/2016/assets/img/logos.svg#au-en", 
  "origin": "https://cdn.au.dk",
  "protocol": "https:",
  "host": "cdn.au.dk",
  "hostname": "cdn.au.dk",
  "port": "",
  "pathname": "/2016/assets/img/logos.svg",
  "search": "",
  "hash": "#au-en"
}
document.contentType; // =>
"image/svg+xml"
```

**Comment by svnhub** [comment]
This is fixed in the next release
