### ISSUE TITLE
Firefox add-on ignores "Keep running on this site?" checkbox

### ISSUE THREAD

**Issue by tomgehrmann** [cavi-au/Consent-O-Matic#36]
In Firefox, the add-on ignores the preferences of the user and automatically consents on every site possible.

Tested on Firefox 90.0.2 64-Bit and 91.0 64-Bit.

**Comment by svnhub** [comment]
Just wanted to update the issue with a note saying that this was verified as a valid bug and is being looked into.

**Comment by svnhub** [comment]
The fix for this bug will be included in the next release

**Comment by svnhub** [comment]
Version 1.0.0 with the fix for this issue is being relased, closing the issue
