### ISSUE TITLE
Not able to save cookie warning

### ISSUE THREAD

**Issue by mrx23dot** [cavi-au/Consent-O-Matic#368]
https://stackoverflow.com
gave this error to me, and I had to acknowledge click it,
which is weird since I retain cookies and auto logged in on visit.

`We couldn’t save your cookie preferences. Please adjust your browser settings or disable ad blocking. You can access your cookie settings at any time by clicking “Cookie Settings” in the footer.`

Also handling the closable consent window takes like 4seconds, it's faster if I manually decline it.

**Comment by svnhub** [comment]
What browser did this happen in and does it still happen?

**Comment by mrx23dot** [comment]
I retested it's no longer an issue.
Firefox 115.8
