### ISSUE TITLE
Residue warning boxes not hid

### ISSUE THREAD

**Issue by mrx23dot** [cavi-au/Consent-O-Matic#369]
I have auto cookie clean up after I close Firefox by default.

So visiting **e.g.** :
`https://codebeautify.org/hex-string-converter`

displays notice pop up annoyance, every time after I startup/clear cookies:

`We use cookies to personalise content and ads, to provide social media features and to analyse our traffic. We also share information about your use of our site with our social media, advertising and analytics partners. See details`

Could we hide every residue too by default, same way as this addon does?
`https://www.i-dont-care-about-cookies.eu/`

The benefit of Consent-O-Matic is that it also forces tracking rejection, not just hides question pop ups.

**Comment by svnhub** [comment]
Could you post a few screenshots of what is happening? For me it seems to handle the entire sourcepoint popup, leaving nothing on screen but the hex-string-converter and no residue

**Comment by mrx23dot** [comment]
Retested it on Firefox, no longer an issue
