### ISSUE TITLE
Enable globalprivacycontrol

### ISSUE THREAD

**Issue by mrx23dot** [cavi-au/Consent-O-Matic#370]
Could this addon enable these Firefox global flags too?

```
about:config
privacy.donottrackheader.enabled	true	
privacy.globalprivacycontrol.enabled	true
```

This is the new version of DoNotTrack preference. By law websites must obey it.
https://blog.mozilla.org/netpolicy/2021/10/28/implementing-global-privacy-control/

so we wouldn't have to do it manually.

**Comment by svnhub** [comment]
These are under Website Privacy Settings under Settings -> Privacy and Security in the Firefox settings. No need to include them in this extension too.

![image](https://github.com/cavi-au/Consent-O-Matic/assets/13135124/84dcdcee-c221-45a9-a992-95e53e297c62)
