### ISSUE TITLE
Invalid Rulelist JSON breaks new installs.

### ISSUE THREAD

**Issue by StoobertB** [cavi-au/Consent-O-Matic#373]
https://github.com/cavi-au/Consent-O-Matic/blob/e5cba137292ad6285f55d64f00b9702c6048307a/rules-list.json#L187-L190

I've just installed Consent-O-Matic on a new system and it wasn't working at all. I thought it may have something to do with Firefox being managed by my org, but I saw in the debug logs that it couldn't parse the JSON for the rules lists, which was updated prior to my fresh install.

**Comment by AUToelboell** [comment]
Thanks for noticing. It has been fixed, you can either wait between 22-48 hours, or go into the plugin under the "Rule Lists" tab and press "Update Rules Now"
