### ISSUE TITLE
"Keep running on this site?" doesn't work on onvista.de

### ISSUE THREAD

**Issue by joextra** [cavi-au/Consent-O-Matic#378]
I want to disable Consent-O-Matic on https://www.onvista.de/, because it doesn't work well there, but Consent-O-Matic ignores it.

**Comment by svnhub** [comment]
Disabling auto-run on an iframe popup from a different domain (https://cdn.privacy-mgmt.com) than the one used for the main page (https://www.onvista.de/) ought to have worked but clearly doesn't. I can confirm this bug.

**Comment by svnhub** [comment]
I'm assuming this was from Firefox? If so then this is fixed in the next release
