### ISSUE TITLE
Request: Prepare for upcoming Firefox Android mobile add-on support

### ISSUE THREAD

**Issue by xxyxxyxyx1** [cavi-au/Consent-O-Matic#396]
The Android version of Firefox currently allows for a small number of add-ons to be installed: 
https://addons.mozilla.org/en-US/android/

This policy will be expanded to allow general installation of Firefox desktop add-ons in Firefox Android by the end of 2023:
https://blog.mozilla.org/addons/2023/09/27/test-firefox-android-extensions-and-help-developers-prepare-for-an-open-mobile-ecosystem-in-december/

It would be great to have COM working on Firefox Android. Manually handling a popup is even more difficult and unpleasant on mobile than on desktop. 

I have downloaded Firefox Android Beta and installed COM, but it does not seem to do anything. An update may be required for compatibility with Firefox  Android. The page linked above includes information for developers about preparing an add-on for Firefox Android release.

I am not a developer, but I would be happy to test a patched version of COM in my Firefox Android Beta if this would be helpful/possible. 

Thank you for making my favorite add-on.

**Comment by xxyxxyxyx1** [comment]
Here is [a new blog post](https://blog.mozilla.org/addons/2023/11/01/is-your-extension-ready-for-firefox-for-android/) from Mozilla on this topic, which includes:
- links to instructions for developers to follow 
- an offer of a free tshirt to developers who add Android compatibility 🤣

**Comment by carnager** [comment]
CoM works just fine for me on mobile for several months now. Using a custom add-ons collection in Firefox nightly. The settings page could need some tweaks, but apart from that it works.

**Comment by xxyxxyxyx1** [comment]
I have just tried again with Firefox Beta, and CoM seems to be working now. I'm not sure if there was an update to the Beta, or perhaps I just needed to restart the phone for the add-on to start running...

**Comment by vmkalbskopf** [comment]
> It seems to be just working fine, been using it on mobile myself for a while now - if you notice any specific problems with it please open a new issue

Are you running the beta? Or full release?

**Comment by svnhub** [comment]
> Are you running the beta? Or full release?

This has been via the custom AMO addon lists in the nightly version of Firefox for Mobile with both the official 1.0.12 and the upcoming 1.0.13 releases of CoM. Soon we should be on the mobile AMO site as well, so it will be a lot easier to install (just pick it from the extension site like on desktop).

**Comment by vmkalbskopf** [comment]
Thanks. That explains why I don't see it in the extension site.
