### ISSUE TITLE
Feature request - Add to Microsoft Edge add-ons / extensions

### ISSUE THREAD

**Issue by o-l-a-v** [cavi-au/Consent-O-Matic#407]
Please add Consent-O-Matic to [Microsoft Edge add-ons / extensions](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home) too, so that one doesn't have to enable installing extensions from Chrome store on Edge.

Doc on "Publish a Microsoft Edge extension":

* https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension

**Comment by jimmysmits** [comment]
Particularly useful when the Chrome Web Store is blocked through corporate policy :)

**Comment by svnhub** [comment]
This is rolling out with v1.1.0, bound to be released over the next week or so

**Comment by jimmysmits** [comment]
@svnhub v1.1.0 has released last month, but I still don't see it available through the Microsoft Edge Add-ons store

<img width="1406" alt="image" src="https://github.com/cavi-au/Consent-O-Matic/assets/61211859/a850ea68-be78-4039-9fbb-f803480adc6f">

**Comment by svnhub** [comment]
v1.1.0 is here: https://microsoftedge.microsoft.com/addons/detail/consentomatic/eflcfflijdiekjkegjghbchoncjhfkda
v1.1.3 (releasing right now) will be searchable too, but it will take a few weeks because of the review process

**Comment by svnhub** [comment]
It is now searchable in the Edge Extension Store
