### ISSUE TITLE
Not working for Youtube

### ISSUE THREAD

**Issue by nPHYN1T3** [cavi-au/Consent-O-Matic#41]
I'm constantly using TOR via the real TOR browser or Brave Private/Tor windows and this never works on Youtube. This may be an issue on other sites as well but I rarely use/visit other sites that nag about this in general so I don't have a lot of potential to spot this failing elsewhere.

**Comment by tennox** [comment]
Duplicate of https://github.com/cavi-au/Consent-O-Matic/issues/25
/close

**Comment by nPHYN1T3** [comment]
Duplicate indeed but I can see how I didn't find the other one when initially checking if it was already reported, that title is horrid. Either way given that was reported in 2020, almost a year before mine I'm guessing this is either dead or this issue will never be fixed.
