### ISSUE TITLE
Ready for firefox on android?

### ISSUE THREAD

**Issue by derTobsch** [cavi-au/Consent-O-Matic#415]
I like this Add-On a lot. Thanks for your work in this!

Do you know what you need to do to get this Add-On to Firefox on Android? Since version 120 the Add-On Store allows to install further Add-Ons and it would be great to have this Add-On on Android.

see https://www.mozilla.org/en-US/firefox/android/120.0/releasenotes/

**Comment by wildwizzy** [comment]
To get this Add-On working on Android browse to this address on your device in Firefox:

https://addons.mozilla.org/en-GB/firefox/addon/consent-o-matic/

Then click on Add to Firefox and it will install in the usual way. 

You can use this method to add any Firefox Add-On to the Android Firefox browser. 

I agree it would be great to have this Add-On in the Android approved list, but if not we have the workaround described above.

**Comment by rugk** [comment]
BTW FYI since [recently opened stable Firefox for all add-ons on AMO](https://blog.mozilla.org/addons/2023/11/28/open-extensions-on-firefox-for-android-debut-december-14-but-you-can-get-a-sneak-peek-today/), so you don't need that list workaround anymore. Just go to https://addons.mozilla.org/ and install the extension.

**Comment by derTobsch** [comment]
> BTW FYI since [recently opened stable Firefox for all add-ons on AMO](https://blog.mozilla.org/addons/2023/11/28/open-extensions-on-firefox-for-android-debut-december-14-but-you-can-get-a-sneak-peek-today/), so you don't need that list workaround anymore. Just go to https://addons.mozilla.org/ and install the extension.

I think we can close this.

**Comment by ikke-t** [comment]
I tried to get this to FF on two different androids. It is not on the list. If you search this plugin, it goes to another one:

https://addons.mozilla.org/fi/android/addon/super-agent/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

So I don't think this should be closed yet.

**Comment by noodlejetski** [comment]
I used to be able to install the addon on mobile for a while, as well as find it on the AMO website when searching on my Android phone and tablet, but it seems that's not the case anymore. the search results display only the addon visible on the screenshot in the previous comment, and if I open the direct link to the addon's page, the button is greyed out on mobile.

**Comment by bjo81** [comment]
I used it also on Android but it seems gone.

**Comment by igalic** [comment]
setting up a new phone and can't install this extension any more.

is there anything we need to enable in Firefox?

**Comment by asgeirrr** [comment]
I was able to install the extension on Android by switching to the desktop version of the site. The button was no longer grayed out. It seems to work as expected after installation 😉

**Comment by Ririshi** [comment]
The workaround that @asgeirrr commented worked for me, too. Also, in the long term, marking this addon as mobile-friendly would be nice so it will show up in the Android-compatible list.

**Comment by svnhub** [comment]
We have just released version 1.1.3 which should again support Firefox on Android browsers with the new manifest v3 build. It should be available through the Mozilla addon site in a few hours.

**Comment by bbigras** [comment]
It's available now.
