### ISSUE TITLE
questions: how/help to contribute & this project still being developed?

### ISSUE THREAD

**Issue by jolan-b** [cavi-au/Consent-O-Matic#422]
Hi,

I really like this extension, which saves us an enormous amount of time. And that's why I'd also like to contribute to the project, in order to add CMPs that aren't yet registered and that persist when I'm browsing and when others are browsing.

I've tried fiddling around to add new rules but to no avail. Is there an explanatory video, for example? Or documentation for newbies?

Finally, is the project kept up to date? If I venture to make pull requests to add new CMPs, will they really be implemented?

Thank you, cya

**Comment by AUToelboell** [comment]
Hi, This project is still being developed. You are more than welcome to contribute, the easiest way, is to use the rule editor, which is found when clicking on the Consent-O-Matic plugin, click "More add-on Settings" -> "Rule List" -> "Open Rule editor".  I would recommend you to take a look on some of these rules and the documentation which can be found in the "README", even though its for json, but the names are still the same.  If you want to contribute you make a pull request with the rule added under the folder "Rules" and updating "rules-list.json" accordingly. 

Best reagards
