### ISSUE TITLE
Thomas Krenn ends up in weird state with somehow-overlayed text when triggered

### ISSUE THREAD

**Issue by rugk** [cavi-au/Consent-O-Matic#423]
## STR

1. Visit https://www.thomas-krenn.com/en/wiki/SMART_Attributes_documentation

### What happens
![grafik](https://github.com/cavi-au/Consent-O-Matic/assets/11966684/b684202d-e408-41a7-887d-23904ae266d6)

### What should happen

No such overlaying

## System
Firefox 121.0

**Comment by AUToelboell** [comment]
Thanks for reporting it should be fixed by now
