### ISSUE TITLE
Pepper handling automatically clicks "Add deal alarm" button

### ISSUE THREAD

**Issue by rugk** [cavi-au/Consent-O-Matic#425]
## STR

E.g. go and search for https://www.mydealz.de/search?q=abcdefTEST (if logged in)

It will automatically press this button:
![grafik](https://github.com/cavi-au/Consent-O-Matic/assets/11966684/be45cb70-5ae6-4dbf-9c5c-c57c0b364e62)

Thus, this will totally spam your feed… :see_no_evil: 

### What should happen

Not do that.

No wonder these are my top hits lol:
![grafik](https://github.com/cavi-au/Consent-O-Matic/assets/11966684/7c0ef00d-0699-4274-a7a2-4152fd1480aa)

## System

Firefox 121.0 (Fedora/Linux)
See also: https://github.com/cavi-au/Consent-O-Matic/issues/418

**Comment by MagicLegend** [comment]
Can confirm this is (unsurprisingly, given that they re-use the UI across regions) also an issue on https://nl.pepper.com.

Firefox 121.0, MacOS 14.1.2 (23B92)

**Comment by AUToelboell** [comment]
Thanks for the reported issue. The issue should be fixed by know.

**Comment by MagicLegend** [comment]
Thank you!
