### ISSUE TITLE
Per domain rules

### ISSUE THREAD

**Issue by terokorp** [cavi-au/Consent-O-Matic#43]
Some websites requires sometimes special rules, like https://assetstore.unity.com/ requires Targeting Cookies to see videos
I would like to able to set like all pages has these settings, but this specific domain has also Targeting Cookies allowed.

**Comment by svnhub** [comment]
This is what the "Keep running on this site" feature is for.

When you encounter a site where you want to deviate from your usual consent preferences you can untick "Keep running on this site" by clicking the add-on icon and then following it up by using the site's GDPR consent manager to set custom preferences.

Did you have some other use case in mind?

**Comment by svnhub** [comment]
No feedback on this one for a year closing the issue as stale
