### ISSUE TITLE
Feature request: Disable the confirmation dialog of "Let us know" button + Pending sites-report

### ISSUE THREAD

**Issue by SvendK** [cavi-au/Consent-O-Matic#44]
_**This is not an issue, and I'm not sure where to put feature requests, so here goes:**_

Hi you wonderful people of the Consent-O-Matic extension.

I'm VERY happy for this extension - and equally VERY unhappy about the current GDPR implementation on the internet, which is why this extension was made. So thank you!

### Disable confirmation dialog on Let us know-button

I use the "Let us know" button daily for sites that the extension can't consent to automatically, and I always click the button and immediately get on with my business, forgetting I have to press OK in the confirmation dialog. 

I'd like a setting to disable this confirmation dialog (clicking the Let us know-button is always OK). That would be nice! :)

### Link to uploaded report / aggregated list of sites pending processing.

I report sites daily and I'm actually unsure if the reportings actually work, as it just closes after clicking OK (which is good! On with the business). I tried with the DevTools network tab to see if the request actually succeeds, but it's hard to find the actual extension network activity.

I'd like a link to either the uploaded report and/or, if you are just aggregating a list, a link to the list, if that could be public.

Best regards
SvendK

**Comment by gerhardbeck** [comment]
Absolutely agreeing. Another tool I used had a confirmation like "tool already reported". That would be great, too

**Comment by Cwpute** [comment]
Heyo, yeah, regarding reports ow websites specifically, i'm not sure either what happens of them. Is there a list we as contributors can go through and try to deal with ?

**Comment by svnhub** [comment]
We're adding a "Don't ask again"-feature to this button in the next release
![image](https://user-images.githubusercontent.com/13135124/159508642-6bc801a3-2750-4545-983a-3707c552a0b4.png)
It will also show a quick little "thank you" when the information has been sent to make sure that it is clear that something actually happened.

At the moment the list of reported sites is mostly used internally to keep track of where to focus these early rule-writing efforts. We will probably have to rethink it slightly now that the addon is gaining more tracktion and more people are getting interested in writing rules.

**Comment by SvendK** [comment]
It's a great plugin and it's magic to see it "in action", clicking those buttons automatically :D
Please, pretty please, keep working on the extension ❤️

**Comment by svnhub** [comment]
I forwarded the request for a public list of reported sites to the research team and they were open to the idea. It will be part of a website that talks a bit more about the add-on.

Release 1.0.0 of the extension is to be released very soon with the confirmation dialog disable feature in it. Closing this issue as solved.
