### ISSUE TITLE
Support for CCPA opt out?

### ISSUE THREAD

**Issue by thirashima** [cavi-au/Consent-O-Matic#442]
Many cookie banners show an option for opting out of the sale of browsing data, if the user is geolocated in California, in order to comply with CCPA protections. Does Consent-O-Matic automatically opt out of this, and if not, is there plans to support it? For an example of how this could work, see the [OptMeowt ](https://github.com/privacy-tech-lab/gpc-optmeowt) extension.

**Comment by AUToelboell** [comment]
If the sites are supported, we support it. Consent-O-Matic, split it into categories. Depending on the users preferences, which can be chosen in the plugin. The plugin either consents to all everything in the category, or deny/opt-out of that everything in the category. Therefore it is up to the individual rule, if the specific site is being supported, and is correctly filled out.
