### ISSUE TITLE
Recommendations for site owners?

### ISSUE THREAD

**Issue by kslstn** [cavi-au/Consent-O-Matic#443]
I see there's a directory with rules for each website. Is there a general approach that makers of consent banners could use adding identifiers, so that not every website ever needs to add a json rules file to the extension?

**Comment by AUToelboell** [comment]
Hi, It looks like each rule only works on a single website, but a lot of the rules like Onetrust_... is named after Onetrust, but is working on a lot of sites. The naming is either "website name" if a website has implemented their own consent banner or "CMP name" if the website is using a CMP. As a site owner, check if Consent-O-Matic works on your site, if you are using a supported CMP, if the CMP you are using, either if it's your own CMP or if the CMP you are using is not supported, or if you are using your own implementation, either request or make a rule/general rule, or make a PR with a rule.
