### ISSUE TITLE
Third party cookie-software use?

### ISSUE THREAD

**Issue by gaga9999** [cavi-au/Consent-O-Matic#444]
hy!
is there a possibility to embedd other add-ons, i.e. when consent-o-matic does nothing, I would like to have https://addons.mozilla.org/de/firefox/addon/i-dont-care-about-cookies/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
handle the cookie?
Thx

**Comment by AUToelboell** [comment]
Hi, Consent-O-Matic runs for a few seconds and if it doesn't find any popups it know, it stops. Don't know how the plugin works, but if you can set a delay of a few seconds, it would probably work.
