### ISSUE TITLE
Mac and iPhone App Stores have version 1.0.12 even though 1.0.13 has been released.

### ISSUE THREAD

**Issue by samikki** [cavi-au/Consent-O-Matic#449]
I love the extension and would like to run the current version.

**Comment by svnhub** [comment]
We are currently still testing the 1.0.13 release via TestFlight before submitting it for final review. It is the first release after switching to XCode 15 and the last release before a big rewrite to support manifest v3 so we are being extra careful. The hope is to have it online in a few weeks from now.

**Comment by svnhub** [comment]
Closing this issue as 1.0.13 was shipped for final review by Apple today and should be in the App Stores for Mac and iOS shortly.
