### ISSUE TITLE
Magisk Module

### ISSUE THREAD

**Issue by B0j4ngl35** [cavi-au/Consent-O-Matic#45]
Would it be too much to ask if this can be created into a Magisk Module for Android?

**Comment by dkgof** [comment]
I am not sure how that would work at all, since it works as a browser extension looking at the rendered pages inside the browser.

**Comment by svnhub** [comment]
Closing this issue as it is currently unclear how to properly support Magisk on Android when the Firefox browser only allows a fixed set of extensions, Chrome doesn't support extensions at all and the Chromium based-browsers with extension support can just add the extension directly from the store without Magisk modules.

Please reopen the issue if you disagree
