### ISSUE TITLE
Installation from source doesn't work on Chrome

### ISSUE THREAD

**Issue by mfulbright** [cavi-au/Consent-O-Matic#452]
I'm trying to install on MacOS Sonoma 14.4.1 but I don't think it matters based on the error.

I'm trying to install from the source. I downloaded a zip of the source and unpacked it in my home dir. I've gone to chrome://extensions, enabled Developer Mode, and am trying to Load the unpacked extension. In the dialog that pops up, I select the "Extension" directory within the source code. I receive the following error:

Failed to load extension

File          ~/consent_o_matic_chrome_extension/Consent-O-Matic-master/Extension
Error       Could not load javascript 'content.js' for script.
                     Could not load manifest.

Looking through the source code, there is indeed no file called content.js. Also looking at manifest.json, it is indeed referencing a file called content.js, in the content_scripts/js section of the JSON.

There is a file called contentScript.js - did the content.js file get renamed but the manifest was never updated?

**Comment by mfulbright** [comment]
There are also these files referenced in the manifest that do not exist in the source code:

content.css
service.js

content.css seems like it probably became the file content.scss in the source code. service.js, I have no idea.

**Comment by svnhub** [comment]
We are changing to manifest v3. Consider using the Chrome extension site to easily install the extension. This is the officially supported method of installation: https://chromewebstore.google.com/detail/consent-o-matic/mdjildafknihdffpkfmmpnpoiajfjnjd

If you insist on not using the official extension site please consider using a release, like the current version 1.0.13 that you can download here https://github.com/cavi-au/Consent-O-Matic/releases

If you must use the source (luke) then you will have to build it using:
npm install
npm run build
and pick the created dist directory for load unpacked.
For this last option you are on your own as things are very much in flux right now. We are in the middle of a fairly extensive rewrite. Expect stuff to be broken.
