### ISSUE TITLE
Breaks ability to translate websites

### ISSUE THREAD

**Issue by Sindicta** [cavi-au/Consent-O-Matic#454]
Recently (in the last 3 days or so) I've been unable to translate web pages (specifically from Greek but I haven't tested other languages) and been simply receiving the "could not translate" error on Edge. I narrowed it down to this extension, disabling it & refreshing always fixes the issue. Not sure what has changed recently as it never used to cause problems.

**Comment by svnhub** [comment]
So translation from Greek to English in Edge doesn't work? Do you have an example page where this happens consistently?
I cannot reproduce this issue in Microsoft Edge 125.0.2535.92 with CoM 1.1.0 from Chrome Extension store on Win10 visiting the kathimerini.gr site where it translates just fine.

Could this be a generic translation issue in Edge that people are reporting is happening randomly and where the solution seems to be to simply select other languages until it works again and then go back to English?

**Comment by Sindicta** [comment]
Yesterday, disabling Consent-O-Matic seemed to fix the issue (and re-enabling it seemed to bring it back) - it was happening consistently on https://www.sklavenitis.gr/ 

Today it's happening again even though I've obviously removed the extension. I'll have to narrow it down to some other extension maybe? but it seems really confusing and annoying to reproduce. Sorry for the confusion. I'll update with info when I can.

**Comment by Sindicta** [comment]
I may have figured out why I (wrongly) assumed Consent-O-Matic was at fault. I disabled a block of extensions at one time to try and narrow the issue down, and then re-enabled them one by one. Then landed on Consent-O-Matic. Privacy badger was in that block.

It seems that on launch, if privacy badger is enabled, translation is broken. Disabling it allows me to translate a page, and once I've done that (on that specific website) I can re-enable privacy badger again with no issues until I restart my browser and the problem returns. Sorry.
