### ISSUE TITLE
Editor toggles not rendered correctly Firefox / char encoding not declared

### ISSUE THREAD

**Issue by a2800276** [cavi-au/Consent-O-Matic#46]
The css for the Rule Editor does not render the toggle thingies (^ and v) as intended in Firefox (96.0 linux) because the character encoding is not declared to be utf-8.

The following rules rules in:   `Extension/editor/scss/main.scss`     

https://github.com/cavi-au/Consent-O-Matic/blob/7d7fd2bd6bf2b662350b0eaeca74db6eba155efe/Extension/editor/scss/main.scss#L162

https://github.com/cavi-au/Consent-O-Matic/blob/7d7fd2bd6bf2b662350b0eaeca74db6eba155efe/Extension/editor/scss/main.scss#L172

render an additional A-circumflex in Firefox (but not in Chrome) : 
![consent-o-magic](https://user-images.githubusercontent.com/35631/151330698-0651f53b-a8b9-43b4-81fb-cd9ec4bdf3af.png)

I assume the intention of the '00a0' char is to add a bit of padding. This could probably be achieved by more css. The underlying problem seems to be that the character encoding is not provided for the html, at least the console complains quite loudly. Not sure how one is supposed to provide the encoding in xpi, but one of:

`<!DOCTYPE html>` at the top of index.html declaring html5 which has utf-8 per default

or

`<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>`

should do the trick. Or use a regular space, that seems to work as well :)

**Comment by svnhub** [comment]
Thanks for the extremely detailed bug description! 

It is indeed a &nbsp; space encoded into css as UTF8 without correctly specifying UTF8 as the page encoding. 
With your fix, things will hopefully look a bit better in Firefox in the future.

![image](https://user-images.githubusercontent.com/13135124/154091575-b37b9339-4b7d-44ac-8c9d-069cc9d28e4a.png)

**Comment by svnhub** [comment]
This was also an issue on Mac+Safari but now fixed in MASTER
