### ISSUE TITLE
Broken manifest for Google Chrome

### ISSUE THREAD

**Issue by palestamp** [cavi-au/Consent-O-Matic#460]
# Problem

I'm trying to install extension from google chrome web store and clicking on the "Add to Chrome" button gives me "Download error: Invalid manifest".

## Version information

Version: 1.1.0
Updated: June 2, 2024

**Comment by svnhub** [comment]
Cannot reproduce this on Chrome 125.0.6422.142 (64bit) on Windows 10
What platform and Chrome version are you using?

**Comment by palestamp** [comment]
I tried to install it on the other  machine with the same system and browser and it works. Probably it is some peculiarity in settings on my first machine. I think this issue can be closed.

**Comment by svnhub** [comment]
Fair enough!
