### ISSUE TITLE
URGENT: iOS app stopped working altogether

### ISSUE THREAD

**Issue by plasmidone** [cavi-au/Consent-O-Matic#461]
The iOS app simply stopped working for no reason. I'm not the only one, multiple reviews saying the same thing in the AppStore. It's been like that for over a week yet there's no mention of this sudden major dysfunction in this GitHub "Issues" page... Please someone look into this and help fix it. Thanks!
![IMG_8077](https://github.com/cavi-au/Consent-O-Matic/assets/162328379/4c248479-4721-472d-b8a6-18afc31da324)

**Comment by Tumleren** [comment]
Same experience for me - after the latest update, the app has mostly or completely stopped working. iOS 17.5.1, app v. 1.1.0

**Comment by svnhub** [comment]
> after the latest update
Latest update of iOS or latest update of Consent-o-matic?
It seems they fixed something in 17.6 Beta that could be related to CoM

**Comment by svnhub** [comment]
Just re-tested it on an iPad with iOS 17.5.1 so this may specifically be a mobile-only bug? Are you all experiencing this on mobile?

**Comment by Tumleren** [comment]
> Just re-tested it on an iPad with iOS 17.5.1 where it works fine - so this may specifically be a mobile-only bug? Are you all experiencing this on mobile?

Yes, I forgot to include in the comment. iPhone 12, iOS 17.5.1, no other Safari extensions besides  CoM v1.1.0. Worked fine prior to the 1.1.0 update

**Comment by svnhub** [comment]
The extension consists of two parts - the frontend/page part that runs whenever you visit a page and the background script (or service-worker) which is responsible for utility functions like fetching updates to rules etc.
It looks like something is basically terminating the background script after a little while on iOS and then never starting it up again even when we try to send messages to it.

Gathering some resources from other people with similar issues:
- https://forums.developer.apple.com/forums/thread/756309 (with minimal example: https://github.com/alexkates/content-script-non-responsive-bug)
- https://forums.developer.apple.com/forums/thread/750330?answerId=785878022#785878022 (feedback indicating it still isn't working)
- https://developer.apple.com/forums/thread/757926

**Comment by svnhub** [comment]
Even if subscribing to other events that will restart the service worker (such as tabs changing), it still doesn't allow the content script to get answers to sendMessage calls. This makes it extremely hard to work-around this bug in any way.

**Comment by svnhub** [comment]
There is no fix yet but we may have stumbled upon a temporary hack that is being pushed into testing right now, it is ugly but if it works it is better than nothing. It will require upgrading our build system to handle multiple manifest files.

Also opened a thread about the issue on Apple's support forum:
https://forums.developer.apple.com/forums/thread/758346

**Comment by plasmidone** [comment]
Is it not possible to roll back the previous iOS version of consent-o-matic which seemed to be working ok? At least until the bug is fixed and a new update is released?

**Comment by svnhub** [comment]
Please try out version 1.1.1 that was released about 47 minutes ago on the app-store

**Comment by Tumleren** [comment]
Having tried about a dozen different sites over maybe 15 minutes, it definitely seems to be working again, and faster than before. iPhone 12, iOS 17.5.1

**Comment by svnhub** [comment]
We have not had any reports of issues since 1.1.1 and the newly released 1.1.3 contains improvements to the build-system to ensure that we have the right manifest files for each platform. Closing this issue.
