### ISSUE TITLE
Add-on install button grayed out in Firefox on Android

### ISSUE THREAD

**Issue by pamoroso** [cavi-au/Consent-O-Matic#465]
I'd like to install the Consent-o-Matic add-on for the Firefox app on my Pixel 7 Pro phone with Android 14.

Searching for `consent-o-matic` from the Firefox Extension Manager yields no relevant resulta. If I visit the [Consent-o-Matic entry](https://addons.mozilla.org/en-US/android/addon/consent-o-matic) the `Add to Firefox` button is grayed out as in this screenshot and I have no way of installing the add-on:

![firefox-addon](https://github.com/cavi-au/Consent-O-Matic/assets/10342479/ddbd7501-864a-4d57-a470-14fbef3610c4)

I have Firefox 127.0.2 and I'm in Italy.

**Comment by asgeirrr** [comment]
I was able to install the extension on Android by switching to the desktop version of the site. The button was no longer grayed out. It seems to work as expected after installation :wink:

**Comment by pamoroso** [comment]
Thanks! Requesting the desktop site did the trick and it's a good workaround, so I'm closing this issue.
