### ISSUE TITLE
gone from chrome store?

### ISSUE THREAD

**Issue by catbabylon** [cavi-au/Consent-O-Matic#468]
I use ungoogled-chromium with NeverDecaf's plugin for installing and updating extensions. I just noticed it give a warning that this addon was removed from the google play store. having just checked the URL, it does seem to have disappeared.

**Comment by norbox** [comment]
Same on Chrome Web store, (not found 404 error) looks like has been removed from there also.

**Comment by nicolaasjan** [comment]
I'd like to know the reason for the removal as well.
Same popup as OP in Ungoogled Chromium:

![screenshot1](https://github.com/user-attachments/assets/4f654013-a044-4c39-9741-2283fdaf6fb5)

**Comment by th0rgall** [comment]
See https://consentomatic.au.dk/ (which is the official home page, linked to from the [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/consent-o-matic/) as well).

> We are aware that Consent-O-Matic is currently missing from the Chrome Extension Store. We are working on a solution.

There's no reason mentioned, but this acknowledgement is something!

**Comment by MidasN** [comment]
We currently don't know yet the reason why Google removed the extension. We think it might have something to do with the recent migration to Manifest V3, but we updated the code so not sure. Unfortunately the person who normally manages this is currently on holiday, so we will have to wait until they return to get to the bottom of this :)

**Comment by catbabylon** [comment]
It's back!
