### ISSUE TITLE
Guardian Cookie Banner not being recognised

### ISSUE THREAD

**Issue by MattTennison** [cavi-au/Consent-O-Matic#47]
Thanks for this extension, it's exactly what I've looking for.

However it doesn't seem to be recognising the Guardian cookie banner, looks like the selectors might need updating:

![guardian-consent-o-matic](https://user-images.githubusercontent.com/1077097/154834411-451b2777-5673-4bb8-89b9-d9e12e2657e9.png)

The extension currently looks for '#cmpContainer' (https://github.com/cavi-au/Consent-O-Matic/blob/038e5982c9cdaa805f7758886083ec5bb9c28433/rules/the_guardian.json#L7) but when I look for that ID on the page I get no results.

**Browser Used:** Brave - Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)

**Website:** https://www.theguardian.com/uk

I'm happy to play around and try submit a PR if you want :smile:

**Comment by svnhub** [comment]
The Guardian uses the sourcepointpopup+sourcepoint_2022 rules now, which were updated 3 days ago but not backported to the add-ons currently on the Firefox/Chrome extension site which still use the old combined rules.json file.

Work is being done on a new and upgraded release of the engine that supports these new individual rule files. The code is in this repository, so you can download and use it already if you would like to beta-test it. Not sure when the official new release is going to be yet.

Flagging the_guardian.json for deletion

**Comment by protist** [comment]
I don't entirely understand the backend, but the Guardian still doesn't seem to work. This issue is from three years ago, but is the new engine not released yet? (I'm using Firefox.) In the meantime, is there a way that we can manually add a rule to work on the Guardian, or are you saying that the older engine will not allow this?
