### ISSUE TITLE
Trustarc Preference Manager

### ISSUE THREAD

**Issue by periode** [cavi-au/Consent-O-Matic#50]
Hello!

First of all, thanks a lot for the project :)

The issue I've encountered is with the automatic filling of the Trustarc Preferences manager (specifially when visiting the Proquest Library websites). Trustarc requires a popup to be opened, and if one has blocked pop ups, then Consent-o-matic gets stuck in a loop.

You can find a test link [here](https://consent-pref.trustarc.com/?type=proquestproduct&site=proquestproduct.com&action=notice&country=de&locale=en&behavior=expressed&layout=default_eu&irm=undefined&from=http://consent.trustarc.com/&preferences=0&autooptout=true&preferences=0&autooptout=true).

Thanks, and let me know if you need any additional information!

**Comment by dkgof** [comment]
What version of Consent-O-Matic did you try with?

Im not getting any weird behaviour on that page?

**Comment by M1Aston** [comment]
Something like this?
https://www.motorauthority.com/news/1134983_here-s-why-jay-leno-doesn-t-own-ferraris

**Comment by periode** [comment]
@dkgof I'm using 1.0.0. The proquest system is also somewhat paywalled (I have to be logged in to my university account), so that might have an impact.

When I re-open the link post above, I also don't get the popup loop behaviour. Same for the link @M1Aston posted.

**Comment by M1Aston** [comment]
Well, this is what I get.
![cookie](https://user-images.githubusercontent.com/43113612/163173398-844d72fc-dba9-4c48-b672-6b6720fbb32c.jpg)

**Comment by dkgof** [comment]
I think i fixed the rules for the motor authority site, at least it seems to work for me.

The problem with trustarc is that they tend to use new classes/structure for their dialog on almost every page, so they are hard to catch.

It was just a rule update, so it should start working in the 1.0 version soon.

**Comment by dkgof** [comment]
I am assuming it is working now, if not reopen a new issue :)
