### ISSUE TITLE
Consent-O-Matic is not properly licensed on the Firefox Add-Ons website

### ISSUE THREAD

**Issue by Nicryc** [cavi-au/Consent-O-Matic#52]
It is licensed as "All Rights Reserved" while it should be as a MIT licensed if I'm not mistaken.

[Here's a link](https://addons.mozilla.org/en-US/firefox/addon/consent-o-matic/) to the add-on page as a proof.

**Comment by dkgof** [comment]
Thank you, was an error for sure :)
