### ISSUE TITLE
Any chance you can make this work on firefox for android?

### ISSUE THREAD

**Issue by dogmax** [cavi-au/Consent-O-Matic#53]
Title. I did search the issues. 

Thank you for this addon :)

**Comment by dkgof** [comment]
I belive that the stable version of firefox for android only allows 18 pre selected addons at the moment. ConsentOMatic used to work for the older version of firefox for android where it was not locked down.

Until they start allowing all addons again, there is not much we can do.

But apparently the nightly version of firefox for android has the ability to load other addons:

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

But the process does not seem straight forward.
