### ISSUE TITLE
Preferences don't seem to stick on genius.com

### ISSUE THREAD

**Issue by emilazy** [cavi-au/Consent-O-Matic#58]
Every time I load a page on genius.com there's a distracting modal flash as the cookie preferences modal pops up and is dismissed, even if I'm directly clicking a link from another page on the site. It seems like the consent settings aren't being remembered, or there's some other issue causing the extension to try and set them on every page load.

I'm using Consent-O-Matic 1.0.2 with Safari 15.4 on macOS 12.3.1. I haven't yet experienced this issue on any other sites but I just installed the extension so it's possible there are others it applies to as well; it seems their consent form is based on OneTrust's CookiePro.

**Comment by dkgof** [comment]
I think it should be fixed now.

The problem was that they took a button from an optanon banner, and moved it into their page menu at the bottom, so Consent-O-Matic though the banner was showing, when it was not.
