### ISSUE TITLE
Differences between this and Auto Cookie Output

### ISSUE THREAD

**Issue by sith-on-mars** [cavi-au/Consent-O-Matic#59]
This is not a bug report, but a discussion.

I'm wondering if the developers are aware of the extension [Auto Cookie Output](https://addons.mozilla.org/en-US/firefox/addon/auto-cookie-optout/)? These two extension seem to achieve the same goal. What are the differences? Seems [Consent-O-Matic](https://github.com/cavi-au/Consent-O-Matic) currently is a better option, since is more under active development and offers more customisation options. Not to mention it has the larger rule lists. Is any possibility that two projects cooperate?

**Comment by dkgof** [comment]
One difference seems to be that Auto Cookie Optout only gives you the possiblity to opt out, where as Consent-O-Matic gives you the ability to say no/yes based on consent category.
