### ISSUE TITLE
Not accepting all cookies

### ISSUE THREAD

**Issue by tomnar** [cavi-au/Consent-O-Matic#65]
The tool does not accept all cookies, although I have chosen to accept everything (all switches set to green).
Test:
- Set extension to accept everything
- Go to https://www.bt.dk/samfund/heunicke-danmark-planlaegger-haandtering-af-mulig-ny-coronaboelge
- See that the video is disabled, because not all cookies were accepted.

**Comment by dkgof** [comment]
I think i fixed it, should work as soon as your rules update. Which is probabely within the next 10 minutes.

The problem was that it pressed the accept selected button, and then after the dialog was hidden, but not removed, it pressed the decline all button.
