### ISSUE TITLE
[Question] Is the extension cookieblock necessary or does it add anything

### ISSUE THREAD

**Issue by bambirombi** [cavi-au/Consent-O-Matic#66]
I see that this extension recommended yours: https://github.com/dibollinger/CookieBlock

After installing your extension, I have seen it works and closes the cookie banner.

What I want to know is if having the above extension installed (already having yours) adds anything from a privacy standpoint, and what is what it adds.

**Comment by Kissaki** [comment]
Consent-O-Matic handles the consent dialogs. It does classify or tamper with cookies.

From the CookieBlock projects readme that you linked, they remove cookies according to their automatic categorization (which may have false positives) and your preference.

The two are tangential. You may want to use CookieBlock if you do not trust providers to provide consent dialogs, or not act according to their consent dialog preference.
