### ISSUE TITLE
Not working on gov.uk and reported multiple times over the past few months

### ISSUE THREAD

**Issue by hingston** [cavi-au/Consent-O-Matic#68]
Just wondering what the "Let us know" button does? I have reported gov.uk and subdomains of it multiple times. I'm sure it's a very popular website. How are the reports categorised and does anyone look at them?

Examples:
https://www.gov.uk/
https://coronavirus.data.gov.uk/

**Comment by dkgof** [comment]
The report button, adds the domain to a list of pages in our database.

The idea is at some point to make the list public, so contributers can see which sites are requested the most.

**Comment by hingston** [comment]
I can see gov.uk works now. Thanks. It would be good to see the list.
