### ISSUE TITLE
Your extension left a blinking " | " on the subtitles on the streaming services I owned when I was watching a movie or series. 

### ISSUE THREAD

**Issue by bettington** [cavi-au/Consent-O-Matic#71]
No idea why, the issue came up when I installed the extension and I was glad for the extension, but the random blinking sign on every subtitle on multiple streaming services, meant that I had to uninstall.

**Comment by dkgof** [comment]
Would it be possible to try again, with only Consent-O-Matic installed, and maybee take a small screenshot of the blinking "|".

Also if you could mention which streaming service it happens on, so we have any chance of trying to reproduce it?

The latest version of Consent-O-Matic should only try to find CMP's to handle within the first 5 seconds, if it finds none, it really should do nothing at all, so this is a bit confusing.

**Comment by svnhub** [comment]
No-one on our team of testers have been able to replicate this issue and there has been no feedback on it for a few months now. Please re-open the issue if this happens again.
