### ISSUE TITLE
App moved from in my face and brilliant to nested in lower right corner and not so brilliant

### ISSUE THREAD

**Issue by scriptor-pro** [cavi-au/Consent-O-Matic#81]
First, Consent-O-Matic is/was/used to be an fantastic addon that saved me a near infinite number of cliks.

Second, here is how C-O-M is behaving recently (Firefox 102, OSX 10.13) : before I had a centered full screen cookie selection pop-up from the visited website. It was automagically filled and disappeared after less than 5 seconds. 
Now I get a small blue rectangle in the lower right corner of my screen. It stays there and as long as it stays there I cannot click on any link on the page.

Is it just me ? Is it a bug or a feature ?

lower right blue rectangle on the following screenshot of the WaPo homepage.

![Screenshot 2022-07-02 at 09-06-56 The Washington Post Breaking News World US DC News and Analysis](https://user-images.githubusercontent.com/64631542/176990936-e3421357-614c-4580-98cb-098e4141f96a.png)

**Comment by dkgof** [comment]
There was a bug in version 1.0.4 where the new picture in picture popup did not dissapear, on firefox and safari.

It should be working now from version 1.0.8.

Furthermore, if you like the old variant better, you can reenable the old style from the hidden debug options:

![image](https://user-images.githubusercontent.com/747208/176991218-79547f59-8cf0-4e78-8022-6c59c2c6e020.png)

**Comment by scriptor-pro** [comment]
I've updated to 1.0.8

how do I access the hidden debug menu ?

**Comment by dkgof** [comment]
Click the debug tab, ive shown it highlighted with red. Then use the option i also highlighted.

**Comment by dkgof** [comment]
Unfortunately i cannot replicate the bug with 1.0.8 on firefox here on windows. Washington post seems to be handled just fine.

**Comment by scriptor-pro** [comment]
I've found the debug menu item ! - thanks a lot - have a nice day
