### ISSUE TITLE
Safari extension does not show up on 

### ISSUE THREAD

**Issue by kasnder** [cavi-au/Consent-O-Matic#84]
I installed the Consent-O-Matic extension on my Mac, following the link to the App Store from the `README.md`.

Unfortunately, the extension does not show up in my Safari extension settings. I can see my other installed extensions though, which all work fine. When I click the button "Quit and Open Safari Extensions Preferences", nothing happens.

macOS version: macOS 12.4
Safari version: 15.5
Mac Model: MacBook Air M1

**Comment by svnhub** [comment]
That's odd.

Just went through the setup process on a similar Mac (not M1, though) with macOS 12.4 and Safari 15.5 where it worked just fine. Now in the process of acquiring an M1-based Mac to check if it is platform-related.

**Comment by svnhub** [comment]
Had 2 people test it on their M1 Macs, no trouble there either.

Does it work if you add the extension to Chrome instead through their extensions on the same machine? (just as a test)

**Comment by kasnder** [comment]
It now works! Weird.

**Comment by svnhub** [comment]
Perfect! That's how we like it

**Comment by anohren** [comment]
I have the same problem on 10.14 (Mojave), where I thought I didn't have it installed but was then surprised that I was only offered to "update" it in App Store. It didn't show up in Safari (Version 13.1 (14609.1.20.111.8)) extensions after the update either.
