### ISSUE TITLE
Console log "Unknown translation key"

### ISSUE THREAD

**Issue by imagoiq** [cavi-au/Consent-O-Matic#86]
Hi,

There are two console log that are appearing on every website that I visit on my Firefox. They doesn't seem to be that important, but it just annoying as a developer to have them in the console 😅 Can you please fix or hide them?

![firefox_slZTkYcVl4](https://user-images.githubusercontent.com/12294151/180020767-11448884-bffb-4086-b99f-296f63fff98e.png)

**Comment by svnhub** [comment]
Can confirm that the translation layer does not check if debugging is enabled on line 1172 in language.js, this is a bug.
However, it also looks like the Language.getString(...) was called with some really odd parameters.

Could you provide the exact version of Firefox and Consent-o-Matic used. Do you have other add-ons that could influence this?

**Comment by imagoiq** [comment]
Hi,
Thanks, just got back from holidays and with my Firefox 104.0b10 and Consen-O-Matic 1.0.8, it doesn't seem to happen. Very likely a conflict with another extension, as you said.
