### ISSUE TITLE
Tooling for Rules.json

### ISSUE THREAD

**Issue by edas** [cavi-au/Consent-O-Matic#9]
Hi

Thank you for your extension.

I tried some rules and working with a large json with so many options was a bit hard for me. To simplify my own tests, I created some tools.

- a validation script (in test.js) which helps point me at error before executing anything (and because the extension is not always throwing errors when something expected is not there)

- and a build script (in build.js) which takes many individual json files and merge them together, and helps me focusing on one CMP at a time.

I did not start a PR because I didn't knew if it was welcomed for this kind of changes, but feel free to take the scripts if you want to, or to tell me to fill a PR for that.

See https://github.com/edas/web-sanitization/tree/master/src

**Comment by dkgof** [comment]
This has somewhat been obsoleted with the addition of the rules editor inside the addon itself. But i am leaving this issue open if anyone else wants to see the tools.

**Comment by svnhub** [comment]
With the version 1.0.0 of the extension that is being released very soon the new rules are split into separate files. Many of the ideas from the tool are now in the extension itself (split rule files, a UI for editing etc) so I'll close this issue.

Thanks for the tool still! Was useful
