### ISSUE TITLE
Addon doesn't work on https://stooq.pl/

### ISSUE THREAD

**Issue by sbstn87** [cavi-au/Consent-O-Matic#92]
Hi, as in the title - the addon does not work on the website: https://stooq.pl/.

It goes into an infinite loop of refreshing the page and cannot move forward to the actual website behind the consent form.

**Comment by svnhub** [comment]
It happens to me too if I manually try to fill out the popup without any extensions activated.

1) Click options
2) Click save these settings

The page reloads and pops up the popup again.

**Comment by svnhub** [comment]
I would argue that in this case the website is broken, not the extension.
