### ISSUE TITLE
Extension interferes with wiki editing, breaking link markup

### ISSUE THREAD

**Issue by HairyDude** [cavi-au/Consent-O-Matic#95]
When editing MediaWiki pages with the source editor, if this extension is turned on, some internal links in the source text get mangled by changing them from double square brackets to single and adding -en inside the link text. For example `[[foo|bar]]` becomes `[foo|bar-en]`. This markup is invalid and results in broken pages. The mangling is also visible in other contexts, e.g. when simply viewing [Help:Links on Wikipedia](https://en.wikipedia.org/wiki/Help:Link#Wikilinks_%28internal_links%29) or [its history](https://en.wikipedia.org/w/index.php?title=Help:Link&oldid=1105423728#Wikilinks_%28internal_links%29). I've verified this with Firefox 104.0.2 on English and German Wikipedias and also the EU4 Wiki. Also verified with Chrome 105.0.5195.127 on English Wikipedia. It doesn't reproduce on Firefox for Android (I have a custom add-on set for Nightly).

With this edit I've also discovered it affects GitHub text fields.

**Comment by svnhub** [comment]
Confirmed

**Comment by svnhub** [comment]
The bug was in the translation system used to process translation tags [[...]] inside the extension pages. The translation code was inadvertently being run not just on the internal extension pages but on all web pages.

This has been fixed and will be included in v.1.0.10 scheduled to be released A.S.A.P.

**Comment by svnhub** [comment]
v.1.0.10 is being released now. It is available in the release list right here on Github already and will be available in App Store, the Chrome/Firefox extension sites, etc. as soon as it has been reviewed.

**Comment by dkgof** [comment]
This bug should be fixed as of 1.0.10.
