### ISSUE TITLE
Manifest V3

### ISSUE THREAD

**Issue by ghost** [cavi-au/Consent-O-Matic#96]
Hi,
I appreciate this extension that you have created. However, I was wondering if it will be affected with the arrival (around January ~~2023~~ **2024**) of [Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/) and if it will continue to work properly on Chromium-based browsers.

Cheers!

**Comment by dkgof** [comment]
As far as i can tell, we do not use any of the removed features. So my best guess would be that it will continue to work. We have not started on rewriting to manifest V3 yet though.

**Comment by dkgof** [comment]
I migrated to manifest v3, in the Manifest V3 branch, and besides some changes that needed to be done, it seems to work just fine.

**Comment by svnhub** [comment]
This is rolling out in v1.1.0 which will be released in all the extension stores over the next week or so
